apisix:
  config_center: yaml
  enable_admin: false

plugins:
  - proxy-rewrite
  - skywalking

plugin_attr:
  skywalking:
    service_name: APISIX
    service_instance_name: "cyborg-dashboard"
    endpoint_addr: http://127.0.0.1:12800
