-!ENCRYPT  
   encryptors:
    aes_encryptor:
      type: AES      
      props:
        aes-key-value: 123456abc  
   tables:
    t_user:
      columns:
        pwd:
          plainColumn: pwd          
          cipherColumn: pwd_cipher          
          encryptorName: aes_encryptor  
          queryWithCipherColumn: false
